name: mdm_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - arrow-cpp=16.1.0
  - async-timeout=4.0.3
  - attrs=23.1.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - blas=1.0
  - boost=1.78.0
  - boost-cpp=1.78.0
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.8.30
  - cairo=1.16.0
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - datasets=2.19.1
  - dill=0.3.8
  - expat=2.6.3
  - filelock=3.13.1
  - fontconfig=2.14.1
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2024.3.1
  - gflags=2.2.2
  - glib=2.80.2
  - glib-tools=2.80.2
  - glog=0.5.0
  - huggingface_hub=0.24.6
  - icu=70.1
  - importlib-metadata=7.0.1
  - intel-openmp=2023.1.0
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libabseil=20240116.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.9.1
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libglib=2.80.2
  - libgrpc=1.62.2
  - libiconv=1.17
  - libnghttp2=1.57.0
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libssh2=1.11.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=18.1.4
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - multidict=6.0.4
  - multiprocess=0.70.15
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openbabel=3.1.1
  - openssl=3.3.2
  - orc=2.0.1
  - packaging=24.1
  - pandas=2.2.2
  - pcre2=10.43
  - pip=24.2
  - pixman=0.40.0
  - pthread-stubs=0.4
  - pyarrow=16.1.0
  - pysocks=1.7.1
  - python=3.10.12
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - python_abi=3.10
  - pytz=2024.1
  - re2=2022.04.01
  - readline=8.2
  - regex=2024.7.24
  - requests=2.32.3
  - s2n=1.3.27
  - setuptools=72.1.0
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tokenizers=0.19.1
  - tqdm=4.66.5
  - transformers=4.44.1
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - urllib3=2.2.2
  - utf8proc=2.6.1
  - wheel=0.43.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.11.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.34.2
      - anndata==0.11.2
      - array-api-compat==1.10.0
      - arviz==0.12.1
      - cachetools==5.5.0
      - cftime==1.6.4.post1
      - click==8.1.7
      - datamol==0.12.5
      - decorator==5.1.1
      - deprecat==2.1.3
      - easydict==1.13
      - et-xmlfile==1.1.0
      - farama-notifications==0.0.4
      - fastjsonschema==2.21.1
      - fastprogress==1.0.3
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==1.0.0
      - idna==3.8
      - importlib-resources==6.4.5
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - lightning-utilities==0.11.8
      - loguru==0.7.2
      - lpips==0.1.4
      - markdown==3.7
      - mofapy2==0.7.2
      - msgpack==1.0.8
      - natsort==8.4.0
      - netcdf4==1.7.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvtx-cu12==12.1.105
      - openpyxl==3.1.5
      - patsy==0.5.6
      - pooch==1.8.2
      - psutil==6.0.0
      - ptflops==0.7.4
      - pydicom==3.0.1
      - pyparsing==3.1.4
      - pypdf2==3.0.1
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pyscf==2.8.0
      - pytorch-fid==0.3.0
      - pytorch-msssim==1.0.0
      - pywavelets==1.8.0
      - pyyaml==6.0.2
      - referencing==0.35.1
      - rpds-py==0.22.3
      - safetensors==0.4.5
      - scipy==1.13.0
      - scooby==0.10.0
      - selfies==2.1.2
      - semver==3.0.2
      - snfpy==0.2.2
      - sympy==1.12
      - tenacity==9.0.0
      - tensorly==0.9.0
      - theano-pymc==1.1.2
      - thop==0.1.1-2209072238
      - torch==2.2.2
      - torch-cluster==1.6.3+pt22cu121
      - torch-fidelity==0.3.0
      - torch-geometric==2.4.0
      - torch-scatter==2.1.2+pt22cu121
      - torch-sparse==0.6.18+pt22cu121
      - torch-spline-conv==1.2.2+pt22cu121
      - torchmetrics==1.5.1
      - triton==2.2.0
      - vtk==9.3.1
      - xarray==2023.12.0
      - xarray-einstats==0.6.0
